name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      upload-artifacts: false
      run-docker-test: false